### ISSUE TITLE
Issue with VikingNPC

### ISSUE THREAD

**Issue by Onins** [meldurson/Portable_Pals#2]
Released tamed viking NPC will spawn many instance of NPC
![image](https://github.com/user-attachments/assets/03f07e2b-6a85-4d37-b645-12fd670fe528)

**Comment by Onins** [comment]
Error

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
PortablePals.CatchPal.ReleaseCreature (Player plr, ItemDrop+ItemData item) (at <2ec7bae331ce415db55765a913d07d5b>:0)
PortablePals.CatchPal.attemptCatch (Player plr, ItemDrop+ItemData item) (at <2ec7bae331ce415db55765a913d07d5b>:0)
PortablePals.Patches.Attack_Start (Attack __instance, Humanoid character, ZSyncAnimation zanim, ItemDrop+ItemData weapon, System.Single& timeSinceLastAttack) (at <2ec7bae331ce415db55765a913d07d5b>:0)
(wrapper dynamic-method) Attack.DMD<Attack::Start>(Attack,Humanoid,UnityEngine.Rigidbody,ZSyncAnimation,CharacterAnimEvent,VisEquipment,ItemDrop/ItemData,Attack,single,single)
(wrapper dynamic-method) Humanoid.DMD<Humanoid::StartAttack>(Humanoid,Character,bool)
Player.PlayerAttackInput (System.Single dt) (at <1f17a254067e41d0b59746dec98ad607>:0)
(wrapper dynamic-method) Player.DMD<Player::FixedUpdate>(Player)

**Comment by meldurson** [comment]
Thank you for letting me know. I think I will disable Vikings from being captured in the Pal Stone as they are completely custom almost everything.

**Comment by Onins** [comment]
that would be better, its weird to make them catchable in the first place. Thanks
