### ISSUE TITLE
DNA not displaying in tooltip

### ISSUE THREAD

**Issue by Onins** [meldurson/Portable_Pals#3]
![image](https://github.com/user-attachments/assets/4e2675ff-0ae1-4bad-9c38-ca7fac7f9391)
![image](https://github.com/user-attachments/assets/38a49413-82f0-40cf-a3e5-874514f4e083)

[LogOutput.log](https://github.com/user-attachments/files/17388882/LogOutput.log)

**Comment by meldurson** [comment]
That is by design. I was not planning on putting the DNA in the tooltip. It is just saved so when released it is not random. If you want to differentiate your creatures in PalStones you can give them a catchy name.

**Comment by Onins** [comment]
Got it, i thought its a bug
